[package]
name = "dyce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["./", "dyce-lang"]
default-members = ["./"]

[dependencies]
rand = "0.8.5"
